version: "3"
services:
    web:
        image: react-app-prod
        deploy:
            replicas: 5
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
        ports:
            - "3000:80"
        networks:
            - webnet
    visualizer:
        image: dockersamples/visualizer:stable
        deploy:
            placement:
                constraints: [node.role == manager]
        ports:
            - "8080:8080"
        networks:
            - webnet
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
networks:
    webnet:
