version: "3"
services:
    reverse-proxy:
        image: traefik
        command: --api --docker
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - net
    web:
        image: react-app
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
        networks:
            - net
        labels:
            - "traefik.backend=react-app"
            - "traefik.frontend.rule=PathPrefixStrip:/react-app"
    api:
        image: dockertestapi
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "0.1"
                    memory: 100M
        networks:
            - net
        labels:
            - "traefik.backend=api"
    visualizer:
        image: dockersamples/visualizer:stable
        deploy:
            placement:
                constraints: [node.role == manager]
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - net
        labels:
            - "traefik.backend=visualizer"
            - "traefik.port=8080"
networks:
    net:
