version: "3"
services:
    ginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
    web:
        image: react-app
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
        environment:
            - VIRTUAL_HOST=localhost
        networks:
            - webnet
    api:
        image: dockertestapi
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "0.1"
                    memory: 100M
        environment:
            - VIRTUAL_HOST=api.localhost
        networks:
            - webnet
    visualizer:
        image: dockersamples/visualizer:stable
        deploy:
            placement:
                constraints: [node.role == manager]
        environment:
            - VIRTUAL_HOST=visualizer.localhost
        networks:
            - webnet
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
networks:
    webnet:
