version: "3"
services:
    ginx-proxy:
        image: jwilder/nginx-proxy
        deploy:
            placement:
                constraints: [node.role == manager]
        ports:
            - "80:80"
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
        networks:
            - webnet

    web:
        image: react-app
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
        expose:
            - "80"
            environment:
                - VIRTUAL_HOST: "localhost"
        networks:
            - webnet

    api:
        image: dockertestapi
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "0.1"
                    memory: 100M
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST: "api.localhost"
        networks:
            - webnet

    visualizer:
        image: dockersamples/visualizer:stable
        deploy:
            placement:
                constraints: [node.role == manager]
        expose:
            - "8080"
        environment:
            - VIRTUAL_HOST: "visualizer.localhost"
        networks:
            - webnet
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
networks:
    webnet:
